name: develop
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-16.04

    services:
      mysql:
        image: mysql:5.6
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: example

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3.8
    - name: Install MySQL lib & client
      run: |
        sudo apt-get install default-libmysqlclient-dev && mysql-client
    - name: Install dependencies
      run: |
        gem install bundler -v 1.17
        bundle install
    - name: Create & Migrate DB
      run: |
        bundle exec rake db:create RAILS_ENV=test
        bundle exec rake db:migrate RAILS_ENV=test
    - name: Run RSpec
      run: bundler exec rspec
